Remove spam fishing detection
mcMMO-Dev/mcMMO pull request #4508
Opened 2021-05-01 02:18 UTC by lexikiq

This issue is patched as of 20w14a

https://bugs.mojang.com/browse/MC-176387

2021-05-01 02:28 UTC, lexikiq commented
hmm.. I guess I'll add a version check
![image](https://user-images.githubusercontent.com/13265322/116768143-7b497400-aa02-11eb-8ff5-6fc89b54c03f.png)

2021-05-01 02:40 UTC, lexikiq commented
I have set the patch to only enable on 1.16+ (hope I used the CompatibilityManager right) and to not launch players for using the exploit. My rationale is explained in the commit's comments.

It's worth noting that this patch is ineffective at best as [vehicles other than minecarts](https://youtu.be/cln5mrh0zDc?t=590) can be used for this exploit as well, but that's outside the scope of this PR...

2021-05-01 13:07 UTC, TheBusyBiscuit requested changes
Just some things that could be improved in my opinion.
But that may just be me

2021-05-01 13:07 UTC, TheBusyBiscuit commented on src/main/java/com/gmail/nossr50/listeners/PlayerListener.java
>                  if(player.isInsideVehicle() && (player.getVehicle() instanceof Minecart || player.getVehicle() instanceof PoweredMinecart))
`PoweredMinecart` is already an extension of `Minecart`. So this check can be simplified.

Also, this may just be me but I feel like the Minecart Flight patch check should go into the if-statement with the Minecart check, not the one with the fishing rod.
It just seems like it makes more sense to me that way.

```suggestion
                       && (heldItem.getType() == Material.FISHING_ROD || player.getInventory().getItemInOffHand().getType() == Material.FISHING_ROD))
            {
                if (player.isInsideVehicle() && player.getVehicle() instanceof Minecart
                    && !mcMMO.getCompatibilityManager().hasPatchedMinecartFlight())
```

2021-05-01 13:07 UTC, TheBusyBiscuit commented on src/main/java/com/gmail/nossr50/listeners/PlayerListener.java
> -                    player.setVelocity(player.getEyeLocation().getDirection().multiply(10));
I didn't really understand why this is here or why it was removed until I saw your commit message.
Perhaps adding a comment about it here may be a good idea.

2021-05-03 22:45 UTC, lexikiq commented on src/main/java/com/gmail/nossr50/listeners/PlayerListener.java
> -                    player.setVelocity(player.getEyeLocation().getDirection().multiply(10));
Not sure why I should add a comment for removed code? Isn't that what version control/commit history is for?

2021-05-04 10:33 UTC, TheBusyBiscuit commented on src/main/java/com/gmail/nossr50/listeners/PlayerListener.java
> -                    player.setVelocity(player.getEyeLocation().getDirection().multiply(10));
Completely fair point.
I was just pointing out my confusion and thought that commenting the line out and adding an explanation right next to it would make it easier to comprehend.

Though I don't have any say here anyway, it was just a suggestion from me which you can feel free to ignore if you want :)

2021-05-31 15:50 UTC, nossr50 commented
The code here was never to patch a flight exploit, it was to prevent getting around anti-afk mechanics for fishing. Which is why I hurled players out of their minecart.

I'm willing to reopen this if there is some other reason to have this.

2021-05-31 15:56 UTC, lexikiq commented
Please reconsider. By hurling players out of their minecarts, without a configurable option at that, you allow players to rocket up into the air exactly like a Trident for completely free. This is a massive exploit that numerous players on our server had been abusing until I modded our server to find and fix the cause. Anti AFK mechanisms don't need to chuck players, you can just dismount them from the minecart and kick them if they remount too much.

2021-05-31 15:57 UTC, nossr50 commented
@lexikiq Thanks for the follow up explanation

2021-05-31 15:57 UTC, nossr50 commented
@lexikiq Does this only affect version 1.16? Why the version check?

2021-05-31 15:58 UTC, lexikiq commented
The version check was under the assumption that the code was trying to fix a vanilla bug which was patched in 1.16

2021-05-31 16:02 UTC, nossr50 commented
@lexikiq Can you remove the version check and just change the PR to remove the ejecting players out of minecarts completely?

2021-05-31 16:07 UTC, lexikiq commented
@nossr50 Done

2021-05-31 16:08 UTC, merged

2021-05-31 16:08 UTC, nossr50 commented
Thank you