Set TNT source in blast mining
mcMMO-Dev/mcMMO pull request #4580
Opened 2021-07-22 01:51 UTC by Pugabyte

2021-07-30 04:44 UTC, lexikiq commented
bump! would appreciate this feature as well. would be nice for logging systems, like grief detection or otherwise

2021-07-30 04:48 UTC, lexikiq approved these changes

2021-07-31 10:12 UTC, TheBusyBiscuit requested changes
There is a huge issue with this though.

The method `TNTPrimed#setSource()` was added on Oct 25th 2020, source:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/4abf9e96df578e4c842c865e50d0933ce0616938#src/main/java/org/bukkit/entity/TNTPrimed.java

In other words, this method was added in 1.16.3 (-SNAPSHOT, 1.16.4 was the first proper release to have included this) and won't be available in prior Minecraft versions.
That's why I am suggesting a version-gated check here, to make sure there won't be any `NoSuchMethodException`s spit out to servers on earlier versions.

2021-07-31 10:12 UTC, TheBusyBiscuit commented on src/main/java/com/gmail/nossr50/skills/mining/MiningManager.java
> +        tnt.setSource(player);
```suggestion
        if (mcMMO.getCompatibilityManager().getMinecraftGameVersion().isAtLeast(1, 16, 4)) {
            tnt.setSource(player);
        }
```

2021-08-02 08:36 UTC, TheBusyBiscuit approved these changes

2021-08-10 21:13 UTC, merged

2021-08-10 21:13 UTC, nossr50 commented
Thank you