Issue/4657 add saturation promotion to food skills
mcMMO-Dev/mcMMO pull request #4659
Opened 2021-11-11 06:43 UTC by Lyther

Currently, food skills only affect hunger but not saturation. I've added the support to increase saturation from food skills.

## Trade-off with Spigot API

Spigot API only has methods to get and set saturation for a player. I have to make a saturation table of each food. Later, if spigot API adds more methods about saturation, I'll refactor my code.

By the way, the food in 1.17 is in the `Hacky support for 1.17` codes, which can run under 1.17 without error.

2021-11-14 02:27 UTC, dodieboy commented
fix #4657

2021-12-08 03:56 UTC, nossr50 commented
I'll try to get this reviewed by Monday

2022-01-01 15:49 UTC, Chew commented
Make sure to include "Fixes #x" in your issue description so it closes if this is merge :)

2022-05-15 22:12 UTC, nossr50 requested changes
Answer the questions when you get a chance, thanks for the PR.

2022-05-15 22:12 UTC, nossr50 commented on src/main/java/com/gmail/nossr50/util/skills/SkillUtils.java
> +        return (currentSaturationLevel + saturationChange);
Do we need a Math.max() for this line? What happens if you go above 20?

2022-05-15 22:12 UTC, nossr50 commented on src/main/java/com/gmail/nossr50/util/MaterialMapStore.java
> +        foodSaturation.put(Material.APPLE, 1.2F);
Where did you pull these values from?

2022-05-15 22:12 UTC, nossr50 commented on src/main/java/com/gmail/nossr50/skills/fishing/FishingManager.java
> +     * Handle the Fisherman's Diet ability about hunger
I suggest changing "about hunger" to "for hunger"

2022-08-07 21:28 UTC, closed without merging