Fixed scoreboard showing vanish players bug
mcMMO-Dev/mcMMO pull request #4774
Opened 2022-06-01 20:23 UTC by KingCreator11

This is a bit of a hack to fix the following issue: https://github.com/mcMMO-Dev/mcMMO/issues/4675. It turns out that issue was caused by another plugin (potentially very frequently used) overloading the Scoreboard `getScore` [method](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scoreboard/Objective.html#getScore(java.lang.String)). This PR only has a single commit which adds an else statement to add a space + a white color code in front of the mctop scoreboard.

I completely understand if you choose to deny this PR as it isn't really an MCMMO issue but I do believe it can help others with the same issue.

2022-06-01 20:50 UTC, nossr50 requested changes
Looks good, do you mind making the changes requested?

2022-06-01 20:50 UTC, nossr50 commented on src/main/java/com/gmail/nossr50/util/scoreboards/ScoreboardWrapper.java
> +import org.bukkit.OfflinePlayer;
Can you remove this unused import?

2022-06-02 00:41 UTC, KingCreator11 commented on src/main/java/com/gmail/nossr50/util/scoreboards/ScoreboardWrapper.java
> +import org.bukkit.OfflinePlayer;
Removed it!

2022-06-08 09:12 UTC, Greymagic27 approved these changes

2022-06-09 21:29 UTC, nossr50 commented
I have to review the implications of this change further before merging

2022-06-10 05:38 UTC, nossr50 commented
I don't think I can accept this PR as I think it could have some unintended side effects.. I wish I could though, if you put in a plugin check (to see if that other plugin is running) then I could add this safely

2022-06-10 05:38 UTC, closed without merging