Small Optimizations
mcMMO-Dev/mcMMO pull request #4893
Opened 2023-05-19 18:00 UTC by Warriorrrr

Adds a whole bunch of small improvements, mainly by cutting down on repeated UserManager#getPlayer and by adopting PaperLib to avoid taking blockstate snapshots when getting blockstates/inventory holders.

As a side effect of no longer using block state snapshots I also unintentionally fixed #4705, since the state with the updated brewing time was never being set back to the brewing stand.

Currently the only place a non-snapshot is held onto is also the alchemy code, I've tested it a bit by destroying a brewing stand in the middle of brewing and everything seemed to work as expected, so I'd call that a win.

2023-05-19 20:44 UTC, nossr50 commented
Thank you warrior, since this is a more significant change than usual I will take my time to review it carefully before merging. Good job 😁

2023-05-29 21:07 UTC, nossr50 requested changes

2023-05-29 21:09 UTC, nossr50 commented
In general it would be preferred if PRs like this could be split up into smaller bite sized pieces, for example if you wanted to put just the PaperLib optimizations in its own PR, otherwise it becomes a lot harder to pull in the work with all the changes needing review.

2023-05-30 11:33 UTC, Warriorrrr commented on src/main/java/com/gmail/nossr50/metadata/ItemMetadataService.java
> +                itemMeta.removeEnchant(Enchantment.DIG_SPEED);
Yes, the implementation just uses a map so the old level is overridden.

2023-06-20 01:45 UTC, nossr50 commented
Would you be up for splitting your PR up into smaller ones?

2023-06-20 01:45 UTC, closed without merging