add off hand to replant in herbalims
mcMMO-Dev/mcMMO pull request #4997
Opened 2024-04-12 23:40 UTC by thiagogebrimm

Fix: https://github.com/mcMMO-Dev/mcMMO/issues/4994

2024-04-13 17:54 UTC, nossr50 requested changes
Looking good, just a few changes needed.

2024-04-13 17:54 UTC, nossr50 commented on src/main/java/com/gmail/nossr50/skills/herbalism/HerbalismManager.java
> -                seed = Material.matchMaterial("CARROT");
We use `matchMaterial` to maintain compatibility with older versions. 
Would you mind changing it back?

2024-04-13 17:54 UTC, nossr50 commented on src/main/java/com/gmail/nossr50/skills/herbalism/HerbalismManager.java
> +        // Remove seed from the appropriate inventory slot (main hand or off-hand)
This would need to happen after the subSkillEvent to give other plugins a chance to cancel this ability.

2024-04-13 17:54 UTC, nossr50 commented on src/main/java/com/gmail/nossr50/skills/herbalism/HerbalismManager.java
> -            playerInventory.removeItem(seedStack);
This is where you would remove the seeds, as this `else` block only happens if the outgoing SubSkillEvent is not cancelled

2024-04-13 21:21 UTC, nossr50 requested changes
You need to check player inventory for seeds as well

2024-04-13 21:21 UTC, nossr50 commented on src/main/java/com/gmail/nossr50/skills/herbalism/HerbalismManager.java
> +            if (playerInventory.getItemInMainHand().getType() == seed) {
These changes are currently only checking for the item being in their main hand or offhand, this doesn't account for the seeds being in their inventory

2024-04-20 22:18 UTC, nossr50 requested changes
Explain how this PR solves the bug? It seems to be missing the off hand seed checks now.

2024-04-20 22:18 UTC, nossr50 commented on src/main/java/com/gmail/nossr50/skills/herbalism/HerbalismManager.java
I'm confused, where did the checks for seeds in the off hand go?

2024-04-21 20:12 UTC, thiagogebrimm commented on src/main/java/com/gmail/nossr50/skills/herbalism/HerbalismManager.java
ops

2024-04-21 21:58 UTC, nossr50 commented
I appreciate the effort @thiagogebrimm , decided to fix this one myself.

2024-04-21 21:58 UTC, closed without merging